### ISSUE TITLE
dolphin.run(render=False)

### ISSUE THREAD

**Issue by Lazarus1992** [altf4/libmelee#33] opened 2019-02-18 12:17 UTC
Ran into a problem with libmelee when trying to set  dolphin.run(render=False) 
It work as intended but setting it back to true did not go back to original settings. It just continued to not render and run in lightning speed. 

Tested: restarting my computer but it did not help. 
Tested: going back to the original example code, did not work

What I needed to do in the end was going in to dolphin Options>Graphics Settings > General  and change the back-end rendered manually

**Comment by altf4** [comment] 2019-04-07 21:21
Blah. libmelee uses the -v flag to dolphin to manually choose the Null renderer. Which... apparently doesn't work anymore?! 

You can see this yourself by just running `dolphin-emu -v NULL` It still renders the game.

I'll try rebasing the custom dolphin to be the latest. Maybe it's fixed there.

**Comment by Lazarus1992** [comment] 2019-04-09 13:36
Thats wierd.  Hope the rebase will fix it. Thanks for the info

Den sön 7 apr. 2019 kl 23:21 skrev AltF4 <notifications@github.com>:

**Comment by altf4** [comment] 2020-05-04 03:24
Confirmed with dolphin devs that this is a bug in dolphin. They're fixing it
https://bugs.dolphin-emu.org/issues/12087

(I guess libmelee is the only thing that uses that CLI arg since it's been broken for a year, heh)

**Comment by altf4** [comment] 2020-07-08 20:52
Update: The bug is fixed in upstream Dolphin, but not the Ishiiruka that Slippi Online uses. Slippi Online is planning on migrating back to mainline dolphin, though. So this ought to be resolved eventually.

**Comment by vladfi1** [comment] 2020-07-12 21:52
libmelee could work around this by setting up the config files itself (maybe it already does this?).

**Comment by altf4** [comment] 2020-08-15 01:10
Crap. Looks like Slippi's Ishiiruka doesn't have a Null renderer. It's not there in the GUI option for me anyway.

**Comment by altf4** [comment] 2020-10-28 01:22
Render option removed.

**Closed as completed by altf4** 2020-10-28 01:22 UTC
